### ISSUE TITLE
After grapheneX Installation ( Unable to start )

### ISSUE THREAD

**Issue by gyanprakashsahu** [grapheneX/grapheneX#114]
Hi Team,
 
I have tried two different options to setup grapheneX.
1- Direct on machine ( Centos )
2- Through Docker 

But i am getting error when start it in both cases. I have attached screenshot. 
![image](https://user-images.githubusercontent.com/10193206/79440632-de34bc80-7ff3-11ea-8447-2dfa3eb5377b.png)
![image](https://user-images.githubusercontent.com/10193206/79440655-e5f46100-7ff3-11ea-852b-c4e08c80cccf.png)

**Comment by bufgix** [comment]
We updated Graphenex. You can update Graphenex with pip

```sh
$ pip install graphenex --upgrade
```
