### ISSUE TITLE
Question about automation point

### ISSUE THREAD

**Issue by gyanprakashsahu** [grapheneX/grapheneX#117]
Guys, I know you are doing well.
If we are looking this product. as automation point of view then we have missing major point.
As per automation,
1-  Configuration automation  (i.e.- services, network, configuration file value  and so on.. which we need for hardening ) **I got this point is fine as of now. because we are in development face and there are option to add new modules as per technical knowledge and requirement **

2- Auto deployment ( on multi server/instance ) **In current project i have found nothing for this. There. is no option to deploy configuration on any remote server/instance. No option to add Inventory list for remote server where we want to deploy** 

3- Log ( i got logs in cli what we ran or deploy services but no option in GUI for that ) **We need to add Logging part also in GUI and **

**Note:** Concern is as of now users need above things.

**Comment by orhun** [comment]
Hi, 
Thanks for the suggestions. We have some questions:
> Configuration automation [...]

What kind of automation you're talking about here? Is this about giving enough technical information while adding new modules?

> Auto deployment [...]

We've thought about deploying grapheneX to other servers/machines and we will probably implement it soon with other brand new features, hopefully.
But still, can you give us slightly more details?

> Log [...]

grapheneX is already showing logs of executed modules on both CLI and Web. What's the "GUI" that you want to see logs?

> **We need to add Logging part also in GUI and **

and... what?

**Comment by orhun** [comment]
Closed due to inactivity.
