### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections' 

### ISSUE THREAD

**Issue by ryanmrestivo** [grapheneX/grapheneX#127]
**Description of bug**
ImportError: cannot import name 'Mapping' from 'collections' (C:\Python311\Lib\collections\__init__.py)

**Log Messages**
Log messages are in screenshot below.  I also face this issue if installing via pip or Python.

**Screenshots**
<img width="1280" alt="Screenshot 2023-06-22 182402" src="https://github.com/grapheneX/grapheneX/assets/53523282/d44500d4-1097-4f92-a0bc-02ef4bfd4367">

**Desktop:**
-Windows 10 22621.1848

**Additional context**
Any information/guidance here would be appreciated!  I realize you support 3.7, though this seems relevant.

**Comment by orhun** [comment]
It is probably a Python incompatibility related dependency version error. Although we have a lock file, we might still need to pin certain dependencies. Which version of Python did you use?

**Comment by ryanmrestivo** [comment]
Hey, thanks for your response -- Python 3.11.4

**Comment by orhun** [comment]
Uh, that's a bit problematic. We simply stopped maintaining this project in 3.7 so these kinds of errors are expected. (definitely fixable tho!)

Is there any chance that you can downgrade to 3.7 and try again to see if the error persists? I recommend using a [pyenv](https://github.com/pyenv/pyenv) or [rye](https://github.com/mitsuhiko/rye) (experimental) for doing so.

**Comment by ryanmrestivo** [comment]
Completely removed python, installed 3.7, new errors haha
<img width="1192" alt="Screenshot 2023-06-23 112151" src="https://github.com/grapheneX/grapheneX/assets/53523282/26390758-8917-449e-a2b8-b119507b5d21">

**Comment by orhun** [comment]
Oh damn, maybe check out https://stackoverflow.com/questions/71850969/importerror-cannot-import-name-run-with-reloader-from-werkzeug-serving

I'm afraid this issue is about to turn into a wormhole 🪱

**Comment by ryanmrestivo** [comment]
You were right, it is a wormhole!

werkzeug doesn't like markupsafe 2.1.3... it looks like markupsafe removed soft_unicode which is causing this error.  (https://github.com/pallets/markupsafe/issues/304)
I attempted to downgrade to 2.0.1, but werkzeug isn't compatible.  Any recommendations on downgrading werkzeug?  Or am I off-track? 

I appreciate your help!
<img width="1270" alt="Screenshot 2023-06-23 113750" src="https://github.com/grapheneX/grapheneX/assets/53523282/b1682909-ecea-437a-a0fd-600f5c18f881">

**Comment by orhun** [comment]
I think the most durable solution would be to support the latest version of all the libraries that are used in the project which means a quite a bit of work. I would say let's go back to the latest Python and focus on somehow solving that error instead of getting stuck in the past.

**Comment by ryanmrestivo** [comment]
Ok - Fixed! Steps taken to remediate so far on python 3.11

 File "C:\Python311\Lib\site-packages\prompt_toolkit\styles\from_dict.py"
 
line 9, in <module>
changed "from collections import Mapping" to "from collections.abc import Mapping"

Then upgraded flask_socketio
pip install --upgrade flask_socketio

Thanks!
<img width="1220" alt="Screenshot 2023-06-23 144408" src="https://github.com/grapheneX/grapheneX/assets/53523282/3dfad1f2-72fb-44f6-8815-cba54c56ddb9">

**Comment by orhun** [comment]
Glad that this is resolved!
