### ISSUE TITLE
Restarting services to apply changes

### ISSUE THREAD

**Issue by jvirgovic** [grapheneX/grapheneX#131]
Hi, I am not sure about Windows, but a lot of these hardening changes actually require to restart services for the changes to take place (either this or reboot).

For example:
- To load some of the network changes, we would need to: sudo sysctl -p
- To apply changes to the sshd_config: sudo service ssh restart
etc...

You get my point; Perhaps it would make sense to add another key to modules.json: "require_restart", or atleast somehow inform the user that the changes will aply after they restart the service themselves, or this can be implemented.

LMK What you think about this. I could add this If you'd be interested, also I'd like to add that this project is really amazing, and you've done a very good job!

**Comment by orhun** [comment]
Thank you for the kind words!

Yeah, adding a key called `require_restart` would be really nice and we can inform the user if that's set to `true` 👍🏼

**Comment by orhun** [comment]
Hey hey, is there any progress on this?

**Comment by jvirgovic** [comment]
Hey, It was a work in progress, but I got caught up in some other stuff. I'll definitely create a PR once I have something, but I'd first like to solve the deprecated 3rd party libs addressed in: #135 before adding new feats

**Comment by orhun** [comment]
Sounds good, thanks a lot!
