### ISSUE TITLE
Update dependencies & Python version

### ISSUE THREAD

**Issue by jvirgovic** [grapheneX/grapheneX#135]
Use this as a centralized point to discuss everything regarding dependencies fixing / porting to newest version of python etc...

**Comment by jvirgovic** [comment]
Regarding: #133

**Comment by jvirgovic** [comment]
grapheneX can now run on Python 3.10 -> Changes introduced in: #137

**Comment by jvirgovic** [comment]
@orhun, I noticed that there's no setup.py file present, but .bumpversion.cfg contains this line:
`[bumpversion:file:setup.py]`

So if user is not building grapheneX from source and is using: pip install graphenex what dependencies are installed if setup.py is not present, and requirements.txt also? Does it read the dependencies from .lock file?

**Comment by orhun** [comment]
hmm I'm not sure. I think we can remove that line.

> Does it read the dependencies from .lock file?

Yup, probably.

**Comment by orhun** [comment]
Just released the new version on PyPI: https://pypi.org/project/graphenex/

**Comment by jvirgovic** [comment]
Nice! Just tested installing and running grapheneX using pip on brand new ubuntu install, and the last thing to figure out is the "from collections import mapping" ImportError.

We successfully got rid of all the other junk errors! Let's make grapheneX great again :100:

**Comment by orhun** [comment]
Lol, hell yeah!

Thanks a lot for your contributions!

**Comment by natechoiniere** [comment]
> Nice! Just tested installing and running grapheneX using pip on brand new ubuntu install, and the last thing to figure out is the "from collections import mapping" ImportError.
> 
> We successfully got rid of all the other junk errors! Let's make grapheneX great again 💯

Ah, so my fresh installation of graphenex on Python 3.11 not working isn't due to me messing something up.

**Comment by jvirgovic** [comment]
Hi @natechoiniere, there are steps to get rid of that one particular error in either of these: #127 / #121. 

If you get any other errors please don't hesitate to share them here, or create issue for them.

**Comment by jvirgovic** [comment]
The mapping ImportError comes from PyInquirer library which, unfortunately is no longer maintained -> [PyInquirer](https://github.com/CITGuru/PyInquirer/issues/159)
[terminaltables](https://github.com/matthewdeanmartin/terminaltables) seems also like a lib that's not maintained anymore. 

It'd be great if we could replace these libraries with others that are up 2 date & well maintained, or even better just use python stdlib tools, and we would get rid of 2 third party imports, meaning that the attack surface of gX would be smaller (sounds familiar huh?)

@orhun please add help wanted label. Someone might take this one up

**Comment by orhun** [comment]
Thanks for the investigating this!

**Comment by jvirgovic** [comment]
Closing in favor of #188. I want to separate python version bumping and outdated lib issues.
