### ISSUE TITLE
Failing to catch exceptions of some hardening commands

### ISSUE THREAD

**Issue by jvirgovic** [grapheneX/grapheneX#136]
When executing some of the hardening commands it looks like the exceptions are not caught for some reason.
Steps:
1. run grapheneX as non-root
2. Open web interface
3. Execute (for example) Set_Permissions_Preload_File, we get this result:
![Screenshot from 2023-09-05 19-47-50](https://github.com/grapheneX/grapheneX/assets/138708600/140898f8-7f65-4823-8e5c-4ae1c456f201)
First of all, it shouldn't try to execute at all, as the "require_superuser" is set to True, so the correct behaviour would be to get this pop-up:
![Screenshot from 2023-09-05 19-53-41](https://github.com/grapheneX/grapheneX/assets/138708600/9b85ddb8-46d0-45c5-bfc8-8b8dc6c64fdd)
It's weird that it actually works in my case if I try to execute any hardening command from "Other" namespace, and it's also incorrectly printed out to stdout
![Screenshot from 2023-09-05 19-48-28](https://github.com/grapheneX/grapheneX/assets/138708600/ecbb206c-b3a9-4d0d-bbf9-e3b63d8d2458)

Need to investigate this further.

**Comment by jvirgovic** [comment]
I investigated further, and this is mostly regarding hardening modules which, change permissions using chmod / chown & contain multiple commands. If we take a look at stdout after executing network/Set_Permissions_System_Configuration:
![Screenshot from 2023-09-12 15-37-56](https://github.com/grapheneX/grapheneX/assets/138708600/e65527ce-d530-496d-9c87-511977cd60f4)
or user/Enable_Password_Control:
![Screenshot from 2023-09-12 15-52-19](https://github.com/grapheneX/grapheneX/assets/138708600/6d73e470-3956-44e9-a6a7-b0eb97fe556b)

These do not get caught by grapheneX in this function:
```
@socketio.on('harden')
@auth_socketio
def hardening_exec(data):
    """Execute the hardening module and send its output to web"""
    try:
        logger.info("Executing the hardening command of " +
                    current_namespace + "/" + data)
        hrd = module_dict[current_namespace][data]
        out = hrd.execute_command()
        print(out)
        emit(data + "_log", {"msg": out, "state": "output"})
        success_msg = "Hardening command executed successfully."
        emit('log_message', {
            'tag': 'success',
            'content': success_msg
        })
        emit(data + "_log", {"state": "success"})
        logger.info(success_msg)
    except PermissionError:
        print("PermissionError caught in web/views.py")
        err_msg = "Insufficient permissions for hardening."
        if check_os():
            err_msg += " Get admin rights and rerun the grapheneX."
        else:
            err_msg += " Try running the grapheneX with sudo."
        emit('log_message', {
            'tag': 'warning',
            'content': err_msg,
            'duration': 2000
        })
        emit(data + "_log", {"state": "error"})
        logger.error(err_msg)
    except Exception as e:
        fail_msg = "Failed to execute hardening command."
        emit('log_message', {
            'tag': 'danger',
            'content': fail_msg,
            'duration': 2000
        })
        emit(data + "_log", {"msg": str(e), "state": "error"})
        logger.error(fail_msg + " " + str(e))
```

As mentioned in #143, adding shell=True to execution function would solve most of our issues here, but than Web UI would break. I would suggest changing all possible modules from multi-cmd to single-cmd.
@orhun what are your thoughts on this?

**Comment by orhun** [comment]
> adding shell=True to execution function would solve most of our issues here, but than Web UI would break. 

I think we can find a way to fix the web UI so I'd happily accept a PR for `shell=True`.

> I would suggest changing all possible modules from multi-cmd to single-cmd.

If that's possible then yes, seems like a good option.
