### ISSUE TITLE
Failure to exec more commands

### ISSUE THREAD

**Issue by jvirgovic** [grapheneX/grapheneX#143]
Hardening modules which execute more than one command are failing. If we execute filesystem/Disable_Uncommon_FS, than we get:
![Screenshot from 2023-09-11 14-53-52](https://github.com/grapheneX/grapheneX/assets/138708600/d5426b4f-92c6-46a2-9c82-89018d3fdf38)

This is happening to all modules which execute more than 1 commands at the same time.
@orhun, Was it working correctly when you were actively maintaining gX a few years ago? None of the changes I've introduced should've resulted in this. Maybe there's something wrong in LinuxExec/run_cmd method.

Modules which only execute 1 command at the time are all behaving correctly.

**Comment by orhun** [comment]
Yeah, they were working fine. Maybe the command is malformed? I never liked that having long-ass strings in JSON, makes debugging so hard. Alternatively, we can support TOML format and convert the commands to multiline scripts which will probably make spotting the error easier.

I'm not sure what's happening on the implementation side but it should be just running that command so I suspect anything is wrong there.

**Comment by jvirgovic** [comment]
Nope, the command is not malformed, because all multi-cmd modules were failing. I debugged this and the problem is that shlex.split(cmd) doesn't correctly interpret "&&" operators as shell command chaining. Passing shell=True fixed this issue for me. I need to do some more testing and will create PR for this.

**Comment by jvirgovic** [comment]
Well, shell=True fixes everything in this case, but for some reason the permission pop-up error will stop working in the Web UI. I am sure there's something wrong with the js / flask stuff.

I need to take a look at the front-end, and also utilise the "require_superuser" field as mentioned in #144
