### ISSUE TITLE
Set up automated Docker builds

### ISSUE THREAD

**Issue by orhun** [grapheneX/grapheneX#156]
**Is your feature request related to a problem? Please describe.**

Docker builds are not automated so we don't know if the image is building fine or not. See #155 

**Describe the solution you'd like**

Create a new GitHub Actions file for building the image (and potentially pushing it to DockerHub / GitHub registry).

**Describe alternatives you've considered**

None.

**Additional context**

We can probably adopt this from another project such as: https://github.com/orhun/halp/blob/main/.github/workflows/docker.yml

**Comment by jvirgovic** [comment]
I'll take this one, @orhun assign 2 me please.

**Comment by orhun** [comment]
You got it!
