### ISSUE TITLE
Revision of each module

### ISSUE THREAD

**Issue by jvirgovic** [grapheneX/grapheneX#162]
Go through all hardening modules and check if the changes are applied or some action needs to be taken after #161 gets merged, and adjust the values in 'require_superuser' correctly.

**Comment by jvirgovic** [comment]
@orhun Please assign to me.

**Comment by orhun** [comment]
Done!

**Comment by jvirgovic** [comment]
Can you also take a look at that PR & share your thoughts?

**Comment by orhun** [comment]
Yup, worked as expected for me.

**Comment by jvirgovic** [comment]
Closing as #164 got merged!
