### ISSUE TITLE
feat: add support for .env file to safely store secret key

### ISSUE THREAD

**Issue by jvirgovic** [grapheneX/grapheneX#196]
### Describe the feature you want

Use `python-dotenv` to store secrets in order to avoid bad practice, such as hardcoding secrets into the source code.

### Describe the problem your feature is related to

Currently gX hardcodes a Flask secret key in the source code. It would be a good idea to add support for `.env` file where the secret key will be stored. If the secret key can't be loaded from the `.env` file then log an error and don't allow the user to start the Web UI.

**Comment by orhun** [comment]
Would be nice to have this!
