### ISSUE TITLE
feat: add rate limiter for /auth endpoint

### ISSUE THREAD

**Issue by jvirgovic** [grapheneX/grapheneX#197]
### Describe the feature you want

Implement a rate limiter for the authentication endpoint. Blocking the user after n attempts for s seconds.

### Describe the problem your feature is related to

Currently gX uses token authentication. If someone has it deployed and available it could be prone to brute-force attacks. The token would probably be hard to brute-force (didn't do the math), but it could create a lot of unnecessary network traffic.

**Comment by orhun** [comment]
Not sure this should be handled on the gX side. If the user has deployed gX somewhere then they are probably capable of handling this via Nginx or Cloudflare.

Also, is there out-of-the-box support for such rate limiting in Flask? Are there any good libraries for it? What's in your mind?

**Comment by jvirgovic** [comment]
> Not sure this should be handled on the gX side. If the user has deployed gX somewhere then they are probably capable of handling this via Nginx or Cloudflare.

That's probably right, I just threw it out as an idea. Not sure If there are any advantages implementing this in the application itself rather than on the web server where it's hosted.

> Also, is there out-of-the-box support for such rate limiting in Flask? Are there any good libraries for it? What's in your mind?

I found well-maintained [flask-limiter](https://github.com/alisaifee/flask-limiter) library that might work.

**Comment by orhun** [comment]
Can you check how easy it would be to integrate? If it is going to require a lot of changes then I'd say let's skip this and let the user handle rate limiting.

**Comment by jvirgovic** [comment]
> Can you check how easy it would be to integrate? If it is going to require a lot of changes then I'd say let's skip this and let the user handle rate limiting.

It wouldn't require a lot of work, but It would introduce a lot of new dependencies, which I am not a big fan of. I think it is probably better to handle this by the web server / reverse proxy. Closing this.
