### ISSUE TITLE
Using abstract classes instead of separating functionality by foldering

### ISSUE THREAD

**Issue by kondanta** [grapheneX/grapheneX#43]
**Is your feature request related to a problem? Please describe.**
It's not. 

**Describe the solution you'd like**
The thing is, you guys have win/linux specific commands in the code base. But those functions literally have the same name. As an example: `run_cmd` function. I believe it can be abstracted out like AbstractOsClasses and can be extended by Linux, Win and MacOS classes.

Also:
- https://12factor.net/

**Describe alternatives you've considered**
None.

**Additional context**
Since I spotted OOP in the code base, choosing solid methodologies should be better. This is just something I think it'd make the code base more maintainable and such. There's no necessity to do the way I mentioned. 

Cheers 🥂

**Comment by orhun** [comment]
Let me know if this looks okay to you: https://github.com/grapheneX/grapheneX/commit/7679b7358ab791172325d4303e85ec2aba4696f6
