### ISSUE TITLE
Provide better module explanations

### ISSUE THREAD

**Issue by BrianAllred** [grapheneX/grapheneX#76]
It would be nice if each module had a short description of why it's recommending a specific change. For example, automatically logging out idle users is intuitive and easy to understand. But what does enabling TCP SYN cookie protection do? Why is it a good idea?

Yes, these things are probably easy to search for on the internet, but it would be nice to get even just a short description.

**Comment by orhun** [comment]
That's true. We will consider this issue for the next version. That would be great if the modules are more explanatory like you said. Thank you for the suggestion.
