### ISSUE TITLE
Pip Install Bug

### ISSUE THREAD

**Issue by Furkhanhash** [grapheneX/grapheneX#77]
**Describe the bug**
pip install graphenex
ERROR:
AttributeError: 'PosixPath' object has no attribute 'read_text'
 .read_text is introduced in Python 3.5.

**Expected behavior**
Successful setup.

**Actual behaviour**
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pCNMf4/graphenex/setup.py", line 5, in <module>
        README = (HERE / "README.md").read_text(encoding="utf-8")
    AttributeError: 'PosixPath' object has no attribute 'read_text'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-pCNMf4/graphenex/

**Steps to reproduce**
pip3 install graphenex

**Desktop (please complete the following information):**
 - OS: Kali Linux

**Comment by bufgix** [comment]
Graphenex minimal supported Python version is 3.7 Update Python and try again
