### ISSUE TITLE
Error found when loading /etc/profile error at desktop loading

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [grapheneX/grapheneX#81]
**Describe the bug**
A error message, at the boot of the desktop (Not the OS in itself or even in the boot phase). Not actual impact from it found so far.

**Log Messages**
Tell us what make you face this issue.
Provide log messages if you get them when the error occur.
Also reproduction steps would be helpful for us to understand the situation.
Message displayed (Some part where in French, the translation i’ve done is correct but might not be the exact formulation in English):
Error found when loading /etc/profile:

/usr/sbin/lightdm-session: line 29 /etc/profile: Rights not granted

As a result the session will not be configured correctly.
You should fix the problem as soon as feasible.

**Expected behavior**
No error displayed. Will load the desktop without any issues, and without pausing it.
**Screenshots**

**Desktop (please complete the following information):**
Content of the neofetch : 
```         eeeeeeeeeeeeeeeee            pm@Velvet4Renaissance 
      eeeeeeeeeeeeeeeeeeeeeee         --------------------- 
    eeeee  eeeeeeeeeeee   eeeee       OS: elementary OS 5.0 Juno x86_64 
  eeee   eeeee       eee     eeee     Host: MS-7918 1.0 
 eeee   eeee          eee     eeee    Kernel: 5.2.0-4.1-liquorix-amd64 
eee    eee            eee       eee   Uptime: 1 hour, 4 mins 
eee   eee            eee        eee   Packages: 3469 
ee    eee           eeee       eeee   Shell: bash 4.4.20 
ee    eee         eeeee      eeeeee   Resolution: 3440x1440 
ee    eee       eeeee      eeeee ee   DE: Pantheon 
eee   eeee   eeeeee      eeeee  eee   WM: Mutter(Gala) 
eee    eeeeeeeeee     eeeeee    eee   Theme: Elementary-x [GTK3] 
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee    Icons: La-Capitaine [GTK3] 
  eeeeeeee eeeeeeeeeeee      eeee     Terminal: io.elementary.t 
    eeeee                 eeeee       CPU: Intel i7-4790 (8) @ 4.000GHz 
      eeeeeee         eeeeeee         GPU: NVIDIA GeForce GTX 1060 6GB 
         eeeeeeeeeeeeeeeee            Memory: 5570MiB / 32110MiB
```

The kernel is a custom one, built automatically from source with it´s couple of general tweaks. https://liquorix.net
**Additional context**
I´m still pretty new as a Linux user, but i think i have still sufficient knowledge of it.
I suppose this could be simply be caused by the user/Set_File_Permissions | Set file permissions of the root user module, and so, doesn´t actually cause any issues in this context.
But as i´ve already said, I consider myself still pretty new to really say to myself that this should be indeed true, wanted to still report it to ask if that was actually the case.

**Comment by orhun** [comment]
Like you said, it might be about a module you executed the hardening command of. (Maybe user/Set_File_Permissions)
But before checking what the module effects on your system, you can search the error and try to fix the problem. Following links might be helpful:
https://askubuntu.com/questions/966775/error-found-when-loading-etc-profile
https://askubuntu.com/questions/913410/cant-login-through-gui-16-04/939061
Also we can add a warning message to the module description (or even remove the module if it's seriously effecting the system) depending on your systems status. Keep us updated and we'll take action.

**Comment by loqs** [comment]
https://github.com/grapheneX/grapheneX/blob/d9978e012f5ffb29140bbd26b63f045a17458c6d/graphenex/modules.json#L364
See also https://bbs.archlinux.org/profile.php?id=80022

**Comment by loqs** [comment]
@keylo99 is there any more information you require to take action?

**Comment by orhun** [comment]
I'll be creating a task for searching this issue in detail based on this issue.

**Comment by loqs** [comment]
Is grapheneX intended to only be used in single user environment?
I ask because of chmod 0700 /etc/profile prevents other users login shells from sourcing it.
It would also be consistant with chmod 02750 /bin/sudo removes setuid from sudo but adds setgid e.t.c.
This would explain PoorPocketsMcNewHold issue.

**Comment by PoorPocketsMcNewHold** [comment]
Well, The fact is that, on my Elementary OS setupp, I indeed only have one user here, having also removed that sort of guest user they have by default.

-------- Message d'origine --------

**Comment by loqs** [comment]
@PoorPocketsMcNewHold the only login user on your system is root?
Does chmod 644 /etc/profile resolve the issue?

**Comment by orhun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Issue #81](https://trello.com/c/6k0Ee02b/63-fix-issue-81)

**Comment by loqs** [comment]
@keylo99 have you considered reverting all the commands added by ac1ef5275d461448e0ca2c10f105be0825bbdd52?

1. Enable password change control to root user
- description does not match rule
2. Set file permissions
- broken command
3. Set permissions on network settings
- permissions issue I previously documented
4. Set permissions on users
- unclear description
- strange permissions
 - does not change the permissions on /run/utmp and /var/log/wtmp or /proc so data still available
5. Set permissions on system configuration
- unclear description
- strange permissions
6. Set permissions on sensitive system files to firewall
- misleading description none of the files modified are for firewall management
/etc/profile global shell configuration file
/etc/hosts.allow tcp wrappers
/etc/mtab symlink to /proc/self/mounts or unused under systemd
/etc/utmp old location for /run/utmp
/var/adm/wtmp old location for /var/log/wtmp
/etc/syslog.pid old location for /run/syslog.pid
7. Set permissions on sensitive system files to kernel
- Files not present / used under systemd
8. Set permissions on privelege escalation
- strange permissions

Applicable to all rules in the commit:
- Marked as not requiring superuser privileges yet operate on files conventionally owned and only writable root
- Even if a command fails using ; the rest of the shell statement will be executed
- No test coverage
- Commit description does not cover the intent for the rules

**Comment by orhun** [comment]
I've considered the changes @loqs requested and I'm thinking of opening a pull request ([~](https://github.com/grapheneX/grapheneX/compare/dev...keylo99:dev)) if the problem solved. Can you give us information @PoorPocketsMcNewHold?

**Comment by PoorPocketsMcNewHold** [comment]
[**@keylo99**](https://github.com/keylo99) commented on [Aug 17, 2019, 3:44 PM GMT+2](https://github.com/grapheneX/grapheneX/issues/81#issuecomment-522238213 "2019-08-17T13:44:20Z - Replied by Github Reply Comments"):
> I've considered the changes [@loqs](https://github.com/loqs) requested and I'm thinking of opening a pull request ([~](https://github.com/grapheneX/grapheneX/compare/dev...keylo99:dev)) if the problem solved. Can you give us information [@PoorPocketsMcNewHold](https://github.com/PoorPocketsMcNewHold)?

Sorry for the late answer, I was on vacation during the duration of this last activity on this issue, and couldn’t operate on my computer.
As suggested by @loqs `chmod 644 /etc/profile` did fix this issue at boot.
