### ISSUE TITLE
Web Interface | Already used address situation

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [grapheneX/grapheneX#82]
**Is your feature request related to a problem? Please describe.**
Ever since i’ve created my IPFS node, grapheneX can’t use the default port of 8080 for its web interface ` An error occurred: [Errno 98] Address already in use` _(Might want to correct this typo in Error btw)_
That's indeed where my IPFS is setup at, this can easily be fixed by using another port by using the [host:port] argument.
**Describe the solution you'd like**
Have a prompt of grapheneX when setting him to start its web interface at a specific address and/or port, to ask to save this address as the default one next. Can easily be changed by default once again, by using -localhost:8080 or maybe with the inclusion of a -default argument
**Describe alternatives you've considered**
I’ve considered suggesting to auto-save it, but a user might want to use a specific port for only specific occasions.
I’ve also thought of having grapheneX have a backup default address that it would try if the default one was already used, but this might be causing some issues if it actually bothers with the user web setup.
Same goes, for trying a random port, or even worse, scanning all the available ones.
**Additional context**
However, as grapheneX modules are habitually ¨Setup once, and forget about it¨, I suppose this isn’t really needed.

**Comment by orhun** [comment]
> However, as grapheneX modules are habitually ¨Setup once, and forget about it¨, I suppose this isn’t really needed.

That's so true. You can change the default port in a hard way (with editing files) or use the `host:port` argument in the terminal. I think there's not much to do in our side here.

**Comment by PoorPocketsMcNewHold** [comment]
Well, The thing is that as the template said, This issue was actually a suggestion to change how grapheneX react to an already used address port when trying to start up its Internet interface.
I’ve indeed known that I could start it with by precising another address and port (And it did worked, thanks to that) but feel free to disregard this suggestion, as it is pretty trivial for people who actually read carefully the documentation.
